ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

# Hide username in prompt
DEFAULT_USER=$(whoami)

plugins=(git zsh-autosuggestions zsh-syntax-highlighting fzf zsh-interactive-cd)

zstyle ':omz:update' mode disabled

source $ZSH/oh-my-zsh.sh

# Load the shell dotfiles
for file in ~/.dotfiles/shell/{exports.sh,aliases.sh,functions.sh}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done

# ~/.dotfiles/custom/ can be used for custom settings
for file in ~/.dotfiles/custom/{zshrc,exports.sh,aliases.sh,functions.sh}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

## Other programs

# Zoxide
eval "$(zoxide init zsh)"
